# logging.yaml
version: 1
disable_existing_loggers: False

formatters:
  default:
    format: "%(asctime)s %(name)s [%(levelname)s] %(message)s"
    datefmt: "%d-%m-%Y %H:%M:%S"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: default  # uses stderr (error channel in terminal) by default

  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: default
    filename: trace.log
    maxBytes: 10_485_760  # 10 MB max per file
    backupCount: 5  # max 5 backups

loggers:
  # default logger for the api
  catchy:
    handlers: [console, file]  # will send errors both to console and to the log file
    level: DEBUG
    propagate: False

  # uvicorn’s own loggers, they're here so they don't propagate to their root loggers and duplicate in console
  uvicorn:
    handlers: [console]  # could be file as well if necessary but it doesn't feel useful now
    level: INFO
    propagate: False

  uvicorn.error:
    handlers: [console]
    level: INFO
    propagate: False

  uvicorn.access:
    handlers: [console]
    level: INFO
    propagate: False

root:
  level: WARNING
  handlers: [console]
