version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: catchy_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Qwerty123!
      POSTGRES_DB: catchy_entities
    ports:
      - "5432:5432"
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
